name: Documentation Update
description: Suggest improvements or report issues with documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear docs make the project better for everyone.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README.md
        - ROADMAP.md
        - CONTRIBUTING.md
        - API Documentation
        - Setup/Installation Guide
        - Architecture Documentation
        - Code Comments
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing information
        - Incorrect information
        - Outdated information
        - Unclear/confusing explanation
        - Typo or grammar
        - New documentation needed
        - Improvement suggestion
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Document Location
      description: Where is the documentation issue located?
      placeholder: |
        File: docs/SETUP.md
        Section: "Development Setup"
        Line: 42
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current State
      description: What does the documentation currently say (if applicable)?
      placeholder: Copy the current text or describe what's currently there...
    validations:
      required: false

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Change
      description: What should the documentation say instead?
      placeholder: Describe or provide the corrected/improved text...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional information that would help us improve the documentation
      placeholder: Why is this change important? What confusion did it cause?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have verified this is still an issue in the latest version
          required: true
        - label: I am willing to submit a PR to fix this
          required: false
