name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What is the use case?
      placeholder: Describe the problem or need...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work? Describe the desired behavior.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: Describe any alternative approaches...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application would this feature affect?
      options:
        - Backend API
        - Frontend UI
        - AI/Matching Engine
        - Authentication
        - Database
        - Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: dropdown
    id: milestone
    attributes:
      label: Suggested Milestone
      description: Which version/milestone should this be considered for?
      options:
        - v0.2.0 - Backend Skeleton
        - v0.3.0 - Anonymous Session System
        - v0.4.0 - AI Matching Engine
        - v0.5.0 - Employer Verification
        - v0.6.0 - Communication Platform
        - v1.0.0 - MVP Launch
        - Future / Post-MVP
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or examples from other applications
      placeholder: Attach images or provide links...
    validations:
      required: false

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Are there any technical constraints or considerations we should be aware of?
      placeholder: Describe any technical details...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the ROADMAP.md to see if this is already planned
          required: true
        - label: This feature aligns with the project's anonymous-first principles
          required: true
        - label: I am willing to help implement this feature
          required: false
